### ISSUE TITLE
Issue: CSS classes that are needed are getting purged

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#179]
The status badges should all have background colors and text colors, such as: 
![image](https://user-images.githubusercontent.com/4587451/112764180-fe734680-8fcc-11eb-9fbb-5e7b01bf80ff.png)

But none of these classes are resolving in production- the classes are getting purged from the CSS, even though they exist on the elements, resulting in this: 
![image](https://user-images.githubusercontent.com/4587451/112764205-1945bb00-8fcd-11eb-8930-a1134bc0c9e6.png)

Here's the template code: 
```hbs
<span
      class="status status-{{cellitem.linting}}">
      {{cellitem.lintingText}}
</span>
```

And here's and example of the CSS:
```css
.status-exists {
  @apply bg-green-100 text-green-800;
}
```

To do: 
Figure out why and fix it.

**Comment by EndangeredMassa** [comment]
PurgeCSS relies on static analysis to find classes that are used. It can't follow the possibilities of dynamic classes. This is the main reason I've not used it in the past.

You can tell PurgeCSS to keep some classes no matter what. They call it a [safelist](https://purgecss.com/safelisting.html). Tailwind docs say you can specify this [here](https://tailwindcss.com/docs/optimizing-for-production#purge-css-options).

**Comment by alexlafroscia** [comment]
Heh, @EndangeredMassa you beat me to it by a second!

**Comment by MelSumner** [comment]
@EndangeredMassa @alexlafroscia Thank you both so much!!

**Comment by MelSumner** [comment]
> I wrote a lint rule to help catch this issue, if you’re interested!
> 
> https://github.com/movableink/template-lint-plugin/blob/master/docs/rules/require-purgeable-class-names.md

@alexlafroscia So I thought about this, but there are 5 potential states and that seemed like it would be too tedious, especially across four columns. If you wanted to take a look at https://github.com/MelSumner/a11y-automation/blob/main/app/templates/details/index.hbs (the `tbody` lines) and wanted to make any recommendations, I'm open to it! 👍

**Comment by kpfefferle** [comment]
Another alternative to the PurgeCSS `safelist` is to wrap classes that you know you want to avoid purging in PurgeCSS ignore comments. This will ensure that PurgeCSS does not strip them even though the classes don't have a string match in your templates.

```css
/* purgecss start ignore */
.status-exists {
  @apply bg-green-100 text-green-800;
}
/* purgecss end ignore */
```

**Comment by MelSumner** [comment]
Resolved! Thanks for all the help!
