### ISSUE TITLE
Add all automated a11y tool listing

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#228]
Add a section or page that lists all of the currently available linters and testers, with links to each. Include IDE and browser extensions.

- AccessLint
- axe tools
- ember-a11y-test
- Microsoft Accessibility Insights
- lighthouse?

**Comment by amyrlam** [comment]
Hi @MelSumner I can take this issue!

**Comment by amyrlam** [comment]
Update: Sorry for the delay, I will get a PR up this week.

**Comment by MelSumner** [comment]
Resolved with #268
