### ISSUE TITLE
Improve badge accessibility

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#305]
The color contrast for the badges are still not sufficient. Any ideas? 

![image](https://user-images.githubusercontent.com/4587451/134093027-3ec2a983-2eff-4b27-aebd-e52d8ae737a5.png)

**Comment by EndangeredMassa** [comment]
I've seen some systems add texture. When there's text inside, the texture sits to the side of the text:

<img width="294" alt="Screen Shot 2021-09-20 at 7 18 09 PM" src="https://user-images.githubusercontent.com/41545/134093618-cef9ba1b-6804-49c6-9eae-52b409eee6be.png">

When there's no text, the texture runs throughout:

<img width="294" alt="Screen Shot 2021-09-20 at 7 18 16 PM" src="https://user-images.githubusercontent.com/41545/134093620-c0d1c2e2-dd8d-4cf8-a3b1-1ba55e82658f.png">


These examples are from Trello.

**Comment by gnclmorais** [comment]
@MelSumner, what metric are you using for the contrast? I quickly checked with [a Chrome extension](https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf?hl=en) and the labels actually look good:
![image](https://user-images.githubusercontent.com/385232/135979682-521d82d2-9762-4048-9b1e-baa000807a43.png)

**Comment by MelSumner** [comment]
@gnclmorais you're right, it seems like it's passing now. Thanks for helping close this issue!
