### ISSUE TITLE
Improvement: tidy up DOM

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#307]
In order to launch the project quickly, I used Tailwind CSS and UI (I have a license). However, the drawback of this is that the DOM is very cluttered. 

It would be good to remove as many of the extra `<div>` elements as possible and stick with semantic HTML. This will take some work to improve sections of code, but it can be done incrementally.

**Comment by MinThaMie** [comment]
**Templates**
- [ ] Automated tools #329 
- [ ] Violations
- [ ] Index
