### ISSUE TITLE
update font combination

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#31]
update the font combination. 

Requirements: 
- easy to read
- complementary to one another

bonus points for variable fonts that are implemented correctly.

**Comment by lenoraporter** [comment]
I think one flexible font with a variety of font weights would totally work for this use case. I've been loving the Google font Inter.

**Comment by lenoraporter** [comment]
I'll push something up so you can see :)

**Comment by MelSumner** [comment]
This issue seems stale; closing for now. If you still want to take this on @lenoraporter feel free to re-open. 👍
