### ISSUE TITLE
improve styles for status labels

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#32]
the status labels in their current shape are dreadfully unpleasing to look at. Please implement new styles that make them nicer for our eyes to behold.

**Comment by jvmoreira** [comment]
Hey, nice project!
I was playing with some styles and ended up with this, what do you think?

<details open>
    <summary>Badges - 2px rounded border</summary>

<img alt="Status Rounded" src="https://user-images.githubusercontent.com/39390862/96808843-0e6c7600-13f0-11eb-9b7e-f9c98cfd5af5.png">
</details>

<details>
    <summary>Badges - 3px rounded border</summary>

<img alt="Status Rounded" src="https://user-images.githubusercontent.com/39390862/96809983-d108e800-13f1-11eb-9d07-8b4003f79e7a.png">
</details>

<details>
    <summary>Badges - no border radius</summary>

<img alt="Status Rounded" src="https://user-images.githubusercontent.com/39390862/96810250-e847d580-13f1-11eb-9a8b-0845eb955819.png">
</details>

**Comment by MelSumner** [comment]
@jvmoreira these look great- make sure to check the color contrasts so they are themselves accessible- I use https://webaim.org/resources/contrastchecker/ when I need to check colors quickly. 

I think I like the 2px rounded borders but I would also be okay with no border radius. 

Feel free to submit a PR if you would like! 👍
