### ISSUE TITLE
Text is difficult to read

### ISSUE THREAD

**Issue by digilou** [MelSumner/a11y-automation#401]
Today I visited [this site](https://a11y-automation.dev/automated-tools) and found some of the text either impossible or difficult to read:
* The intro text is black on dark blue, making it impossible to read (short of highlighting the text).
* Heading link text (golden yellow on white) of each resource is hard to read.

<img width="445" alt="Screenshot of Automated A11y Tools homepage intro paragraph and first listed resource." src="https://user-images.githubusercontent.com/8865558/188995484-60d0f2dc-8164-436c-841c-c7190077e16d.png">

| Environment | Version |
|------|---------|
| OS | macOS 12.5.1 |
| Firefox | 104.0.2 |
| Mode | dark |

**Comment by digilou** [comment]
Taking a quick peek at source code, this may be a quick fix for the intro text:
`<meta name="color-scheme" content="dark light">`

**Comment by MelSumner** [comment]
I believe I've resolved the issue, please re-open if you still see the issue! 

Screenshot:
![CleanShot 2022-09-08 at 15 08 28](https://user-images.githubusercontent.com/4587451/189216198-6f39ca1b-a0c1-42ae-878a-0cc3c79be125.png)

**Comment by digilou** [comment]
The white text is there @MelSumner!

The only other thing I request is changing the gold-on-white links in each card (in dark mode). They're hard to read also.

**Comment by digilou** [comment]
Perfect! Thanks @MelSumner. Wonderful resource, btw. Hoping to share with other devs in the near future!
