### ISSUE TITLE
Enhancement: Add toggle for light/dark theme

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#409]
Right now, light/dark theme is automatically rendered based on the user's operating system settings. 

It would be a nice enhancement to have a toggle for the theme. The default should be the user's OS settings.

**Comment by mohitkumaragrawal** [comment]
I want to work on this issue, can you assign this to me

**Comment by NNL-Keerthana** [comment]
I would like to work on this issue.
