### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#436]
The last portion of the README is incorrect now that we include linting for other JS frameworks. Prose should be updated to reflect.

**Comment by AshwanthramKL** [comment]
Hey can I work on this?

**Comment by MelSumner** [comment]
@AshwanthramKL sure!

**Comment by AshwanthramKL** [comment]
Hey @MelSumner,

"Inclusion in Documentation
Although this app currently tracks linting from ember-template-lint and testing from axe-core, we have expanded support to include linting for other JavaScript frameworks. If you want to contribute linting support for other frameworks, please follow the format in the existing violations to allow your PR to be accepted/merged more readily."

Would this be correct?

**Comment by MelSumner** [comment]
@AshwanthramKL yeah that could work! It could also be fine to include the others by name and link to them, but really whatever you are comfortable with. The goal is to express that there are several automation tools taken into account, and your suggestion would satisfy that requirement.

**Comment by AshwanthramKL** [comment]
I'm under a bit of a time constraint, so I'll do this for now and update it later with the specific names and links.
