### ISSUE TITLE
improve status labels

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/a11y-automation#6]
The status labels could probably use a better solution (than what is currently in the `detail.hbs` template) to determine what class to add to the template. 

These attributes: `linting`, `testing`, `author`, `manual` all have one of the following values: 

- `exists`
- `couldexist`
- `cannotexist`
- `mustexist`

Based on the value, the label then receives a css class: 

- `.status-exists`
- `.status-couldexist`
- `.status-cannotexist`
- `.status-mustexist`

The helper should also render the text correctly- `couldexist` should render as "could exist".

**Comment by MelSumner** [comment]
For now this is an if/else if statement in the details template. would be good to improve this area.

**Comment by FEDQK** [comment]
Hi @MelSumner 
I updated status lables, please check PR #27

**Comment by MelSumner** [comment]
Resolved with PR #27 - thank you so much @FEDQK 💯
